services:
  db:
    image: mongo:latest
    volumes:
      - poke-vol:/data/db
    # Ports not exposeds
    # ports:
    #   - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ["--auth"]

  mongo-express:
    depends_on:
      - db
    image: mongo-express:latest
    ports:
      - 8080:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ADMINSERVER: ${MONGO_DB_NAME}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: db

  poke-app:
    depends_on:
      - db
      - mongo-express
    image: klerith/pokemon-nest-app:1.0.0
    ports:
      - 3000:3000
    restart: always
    environment:
      MONGODB: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db:27017
      DB_NAME: ${MONGO_DB_NAME}

volumes:
  poke-vol:
    external: false
